#!/bin/sh

exec_pacman() {
    case $1 in
        debian) cat package-lists/packages-deb | tr "\n" " " | xargs apt install -y ;;
        arch) $2 -Syu $(cat package-lists/packages-arch | tr '\n' ' ') --noconfirm;;
    esac
}

if [ ! $# -eq 0 ]
then
    exec_pacman $1 $2
else
    echo "Please specify your os then your package manager.
For debian derrivatives, just do
    # ./install-packages debian
For arch derrivatives, do
    $ ./install-packages arch yay (or any other AUR helper)"
fi
