set number
set autoread
set ignorecase
set hlsearch
set incsearch

command! W execute 'w !doas -- tee % > /dev/null' <bar> edit!

syntax enable

set tabstop=8

set softtabstop=0 

set ts=4 

set sw=4 

set shiftwidth=4

set expandtab smarttab

set et

set ai si wrap

map <space> /

map <C-c> :noh <Return>

map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
map <C-s> :w<Return>

let mapleader="`"

nnoremap <leader>s :sort <Return>

map WQ :wq <Return>
map QQ :q! <Return>

function! NumberToggle()
    if(&nu == 1)
        set nu!
    else
        set nu
    endif
endfunction

nnoremap <leader>q :call NumberToggle()<CR><Return>

function! LineToggle()
    if(&cursorline == 1)
        set cursorline!
    else
        set cursorline
    endif
endfunction

nnoremap <leader>l :call LineToggle()<CR><Return>

function! ToggleColorColumn()
    if(&cc == 80)
        set cc=9999
    else
        set cc=80
    endif
endfunction

nnoremap <leader>c :call ToggleColorColumn()<CR><Return>
