set number
set autoread
set ignorecase
set hlsearch
set incsearch

command! W execute 'w !doas -- tee % > /dev/null' <bar> edit!

syntax enable

set tabstop=8

set softtabstop=0 

set ts=4 

set sw=4 

set shiftwidth=4

set expandtab smarttab

set et

set ai si wrap

map <space> /

map <C-c> :noh <Return>

map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
map <C-s> :w<Return>

let mapleader="`"

nnoremap <leader>s :sort <Return>

map WQ :wq <Return>
map QQ :q! <Return>

function! NumberToggle()
    if(&nu == 1)
        set nu!
    else
        set nu
    endif
endfunction

nnoremap <leader>q :call NumberToggle()<CR><Return>

function! LineToggle()
    if(&cursorline == 1)
        set cursorline!
    else
        set cursorline
    endif
endfunction

nnoremap <leader>l :call LineToggle()<CR><Return>

function! ToggleColorColumn()
    if(&cc == 80)
        set cc=9999
    else
        set cc=80
    endif
endfunction

nnoremap <leader>c :call ToggleColorColumn()<CR><Return>

" indentation rules for FFmpeg: 4 spaces, no tabs
set expandtab
set shiftwidth=4
set softtabstop=4
set cindent
set cinoptions=(0
" Allow tabs in Makefiles.
autocmd FileType make,automake set noexpandtab shiftwidth=8 softtabstop=8
" Trailing whitespace and tabs are forbidden, so highlight them.
" highlight ForbiddenWhitespace ctermbg=red guibg=red
" match ForbiddenWhitespace /\s\+$\|\t/
" Do not highlight spaces at the end of line while typing on that line.
" autocmd InsertEnter * match ForbiddenWhitespace /\t\|\s\+\%#\@<!$/
