name: autoreadme
on:
  push:
    paths:
      - backgrounds/**
jobs:
  autoreadme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Update README
        run: ./deploy-scripts/autoreadme.sh
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: README.md
          commit-msg: Update resources
          github-token: ${{ secrets.DEPLOYTOKEN }}
